// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grfa.proto

package org.apache.giraffa;

public final class GiraffaProtos {
  private GiraffaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UnlocatedBlockProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .hadoop.hdfs.ExtendedBlockProto b = 1;
    boolean hasB();
    org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto getB();
    org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProtoOrBuilder getBOrBuilder();
    
    // required uint64 offset = 2;
    boolean hasOffset();
    long getOffset();
    
    // required bool corrupt = 3;
    boolean hasCorrupt();
    boolean getCorrupt();
    
    // required .hadoop.common.TokenProto blockToken = 4;
    boolean hasBlockToken();
    org.apache.hadoop.security.proto.SecurityProtos.TokenProto getBlockToken();
    org.apache.hadoop.security.proto.SecurityProtos.TokenProtoOrBuilder getBlockTokenOrBuilder();
  }
  public static final class UnlocatedBlockProto extends
      com.google.protobuf.GeneratedMessage
      implements UnlocatedBlockProtoOrBuilder {
    // Use UnlocatedBlockProto.newBuilder() to construct.
    private UnlocatedBlockProto(Builder builder) {
      super(builder);
    }
    private UnlocatedBlockProto(boolean noInit) {}
    
    private static final UnlocatedBlockProto defaultInstance;
    public static UnlocatedBlockProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public UnlocatedBlockProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_UnlocatedBlockProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_UnlocatedBlockProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .hadoop.hdfs.ExtendedBlockProto b = 1;
    public static final int B_FIELD_NUMBER = 1;
    private org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto b_;
    public boolean hasB() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto getB() {
      return b_;
    }
    public org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProtoOrBuilder getBOrBuilder() {
      return b_;
    }
    
    // required uint64 offset = 2;
    public static final int OFFSET_FIELD_NUMBER = 2;
    private long offset_;
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getOffset() {
      return offset_;
    }
    
    // required bool corrupt = 3;
    public static final int CORRUPT_FIELD_NUMBER = 3;
    private boolean corrupt_;
    public boolean hasCorrupt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getCorrupt() {
      return corrupt_;
    }
    
    // required .hadoop.common.TokenProto blockToken = 4;
    public static final int BLOCKTOKEN_FIELD_NUMBER = 4;
    private org.apache.hadoop.security.proto.SecurityProtos.TokenProto blockToken_;
    public boolean hasBlockToken() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public org.apache.hadoop.security.proto.SecurityProtos.TokenProto getBlockToken() {
      return blockToken_;
    }
    public org.apache.hadoop.security.proto.SecurityProtos.TokenProtoOrBuilder getBlockTokenOrBuilder() {
      return blockToken_;
    }
    
    private void initFields() {
      b_ = org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.getDefaultInstance();
      offset_ = 0L;
      corrupt_ = false;
      blockToken_ = org.apache.hadoop.security.proto.SecurityProtos.TokenProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasB()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCorrupt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getB().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBlockToken().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, b_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, offset_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, corrupt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, blockToken_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, b_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, offset_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, corrupt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, blockToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto)) {
        return super.equals(obj);
      }
      org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto other = (org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto) obj;
      
      boolean result = true;
      result = result && (hasB() == other.hasB());
      if (hasB()) {
        result = result && getB()
            .equals(other.getB());
      }
      result = result && (hasOffset() == other.hasOffset());
      if (hasOffset()) {
        result = result && (getOffset()
            == other.getOffset());
      }
      result = result && (hasCorrupt() == other.hasCorrupt());
      if (hasCorrupt()) {
        result = result && (getCorrupt()
            == other.getCorrupt());
      }
      result = result && (hasBlockToken() == other.hasBlockToken());
      if (hasBlockToken()) {
        result = result && getBlockToken()
            .equals(other.getBlockToken());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasB()) {
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getB().hashCode();
      }
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getOffset());
      }
      if (hasCorrupt()) {
        hash = (37 * hash) + CORRUPT_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getCorrupt());
      }
      if (hasBlockToken()) {
        hash = (37 * hash) + BLOCKTOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getBlockToken().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.giraffa.GiraffaProtos.UnlocatedBlockProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_UnlocatedBlockProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_UnlocatedBlockProto_fieldAccessorTable;
      }
      
      // Construct using org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBFieldBuilder();
          getBlockTokenFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (bBuilder_ == null) {
          b_ = org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.getDefaultInstance();
        } else {
          bBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        corrupt_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (blockTokenBuilder_ == null) {
          blockToken_ = org.apache.hadoop.security.proto.SecurityProtos.TokenProto.getDefaultInstance();
        } else {
          blockTokenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto.getDescriptor();
      }
      
      public org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto getDefaultInstanceForType() {
        return org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto.getDefaultInstance();
      }
      
      public org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto build() {
        org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto buildPartial() {
        org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto result = new org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (bBuilder_ == null) {
          result.b_ = b_;
        } else {
          result.b_ = bBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.corrupt_ = corrupt_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (blockTokenBuilder_ == null) {
          result.blockToken_ = blockToken_;
        } else {
          result.blockToken_ = blockTokenBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto) {
          return mergeFrom((org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto other) {
        if (other == org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto.getDefaultInstance()) return this;
        if (other.hasB()) {
          mergeB(other.getB());
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasCorrupt()) {
          setCorrupt(other.getCorrupt());
        }
        if (other.hasBlockToken()) {
          mergeBlockToken(other.getBlockToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasB()) {
          
          return false;
        }
        if (!hasOffset()) {
          
          return false;
        }
        if (!hasCorrupt()) {
          
          return false;
        }
        if (!hasBlockToken()) {
          
          return false;
        }
        if (!getB().isInitialized()) {
          
          return false;
        }
        if (!getBlockToken().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.Builder subBuilder = org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.newBuilder();
              if (hasB()) {
                subBuilder.mergeFrom(getB());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setB(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              offset_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              corrupt_ = input.readBool();
              break;
            }
            case 34: {
              org.apache.hadoop.security.proto.SecurityProtos.TokenProto.Builder subBuilder = org.apache.hadoop.security.proto.SecurityProtos.TokenProto.newBuilder();
              if (hasBlockToken()) {
                subBuilder.mergeFrom(getBlockToken());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBlockToken(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .hadoop.hdfs.ExtendedBlockProto b = 1;
      private org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto b_ = org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto, org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.Builder, org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProtoOrBuilder> bBuilder_;
      public boolean hasB() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto getB() {
        if (bBuilder_ == null) {
          return b_;
        } else {
          return bBuilder_.getMessage();
        }
      }
      public Builder setB(org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto value) {
        if (bBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          b_ = value;
          onChanged();
        } else {
          bBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setB(
          org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.Builder builderForValue) {
        if (bBuilder_ == null) {
          b_ = builderForValue.build();
          onChanged();
        } else {
          bBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeB(org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto value) {
        if (bBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              b_ != org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.getDefaultInstance()) {
            b_ =
              org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.newBuilder(b_).mergeFrom(value).buildPartial();
          } else {
            b_ = value;
          }
          onChanged();
        } else {
          bBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearB() {
        if (bBuilder_ == null) {
          b_ = org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.getDefaultInstance();
          onChanged();
        } else {
          bBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.Builder getBBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBFieldBuilder().getBuilder();
      }
      public org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProtoOrBuilder getBOrBuilder() {
        if (bBuilder_ != null) {
          return bBuilder_.getMessageOrBuilder();
        } else {
          return b_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto, org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.Builder, org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProtoOrBuilder> 
          getBFieldBuilder() {
        if (bBuilder_ == null) {
          bBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto, org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProto.Builder, org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.ExtendedBlockProtoOrBuilder>(
                  b_,
                  getParentForChildren(),
                  isClean());
          b_ = null;
        }
        return bBuilder_;
      }
      
      // required uint64 offset = 2;
      private long offset_ ;
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getOffset() {
        return offset_;
      }
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000002;
        offset_ = value;
        onChanged();
        return this;
      }
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000002);
        offset_ = 0L;
        onChanged();
        return this;
      }
      
      // required bool corrupt = 3;
      private boolean corrupt_ ;
      public boolean hasCorrupt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getCorrupt() {
        return corrupt_;
      }
      public Builder setCorrupt(boolean value) {
        bitField0_ |= 0x00000004;
        corrupt_ = value;
        onChanged();
        return this;
      }
      public Builder clearCorrupt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        corrupt_ = false;
        onChanged();
        return this;
      }
      
      // required .hadoop.common.TokenProto blockToken = 4;
      private org.apache.hadoop.security.proto.SecurityProtos.TokenProto blockToken_ = org.apache.hadoop.security.proto.SecurityProtos.TokenProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.hadoop.security.proto.SecurityProtos.TokenProto, org.apache.hadoop.security.proto.SecurityProtos.TokenProto.Builder, org.apache.hadoop.security.proto.SecurityProtos.TokenProtoOrBuilder> blockTokenBuilder_;
      public boolean hasBlockToken() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public org.apache.hadoop.security.proto.SecurityProtos.TokenProto getBlockToken() {
        if (blockTokenBuilder_ == null) {
          return blockToken_;
        } else {
          return blockTokenBuilder_.getMessage();
        }
      }
      public Builder setBlockToken(org.apache.hadoop.security.proto.SecurityProtos.TokenProto value) {
        if (blockTokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          blockToken_ = value;
          onChanged();
        } else {
          blockTokenBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setBlockToken(
          org.apache.hadoop.security.proto.SecurityProtos.TokenProto.Builder builderForValue) {
        if (blockTokenBuilder_ == null) {
          blockToken_ = builderForValue.build();
          onChanged();
        } else {
          blockTokenBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeBlockToken(org.apache.hadoop.security.proto.SecurityProtos.TokenProto value) {
        if (blockTokenBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              blockToken_ != org.apache.hadoop.security.proto.SecurityProtos.TokenProto.getDefaultInstance()) {
            blockToken_ =
              org.apache.hadoop.security.proto.SecurityProtos.TokenProto.newBuilder(blockToken_).mergeFrom(value).buildPartial();
          } else {
            blockToken_ = value;
          }
          onChanged();
        } else {
          blockTokenBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearBlockToken() {
        if (blockTokenBuilder_ == null) {
          blockToken_ = org.apache.hadoop.security.proto.SecurityProtos.TokenProto.getDefaultInstance();
          onChanged();
        } else {
          blockTokenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public org.apache.hadoop.security.proto.SecurityProtos.TokenProto.Builder getBlockTokenBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getBlockTokenFieldBuilder().getBuilder();
      }
      public org.apache.hadoop.security.proto.SecurityProtos.TokenProtoOrBuilder getBlockTokenOrBuilder() {
        if (blockTokenBuilder_ != null) {
          return blockTokenBuilder_.getMessageOrBuilder();
        } else {
          return blockToken_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.hadoop.security.proto.SecurityProtos.TokenProto, org.apache.hadoop.security.proto.SecurityProtos.TokenProto.Builder, org.apache.hadoop.security.proto.SecurityProtos.TokenProtoOrBuilder> 
          getBlockTokenFieldBuilder() {
        if (blockTokenBuilder_ == null) {
          blockTokenBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.apache.hadoop.security.proto.SecurityProtos.TokenProto, org.apache.hadoop.security.proto.SecurityProtos.TokenProto.Builder, org.apache.hadoop.security.proto.SecurityProtos.TokenProtoOrBuilder>(
                  blockToken_,
                  getParentForChildren(),
                  isClean());
          blockToken_ = null;
        }
        return blockTokenBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:giraffa.UnlocatedBlockProto)
    }
    
    static {
      defaultInstance = new UnlocatedBlockProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:giraffa.UnlocatedBlockProto)
  }
  
  public interface RenameStateProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool flag = 1;
    boolean hasFlag();
    boolean getFlag();
    
    // optional bytes src = 2;
    boolean hasSrc();
    com.google.protobuf.ByteString getSrc();
  }
  public static final class RenameStateProto extends
      com.google.protobuf.GeneratedMessage
      implements RenameStateProtoOrBuilder {
    // Use RenameStateProto.newBuilder() to construct.
    private RenameStateProto(Builder builder) {
      super(builder);
    }
    private RenameStateProto(boolean noInit) {}
    
    private static final RenameStateProto defaultInstance;
    public static RenameStateProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public RenameStateProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_RenameStateProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_RenameStateProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool flag = 1;
    public static final int FLAG_FIELD_NUMBER = 1;
    private boolean flag_;
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getFlag() {
      return flag_;
    }
    
    // optional bytes src = 2;
    public static final int SRC_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString src_;
    public boolean hasSrc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getSrc() {
      return src_;
    }
    
    private void initFields() {
      flag_ = false;
      src_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, src_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, flag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, src_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.giraffa.GiraffaProtos.RenameStateProto)) {
        return super.equals(obj);
      }
      org.apache.giraffa.GiraffaProtos.RenameStateProto other = (org.apache.giraffa.GiraffaProtos.RenameStateProto) obj;
      
      boolean result = true;
      result = result && (hasFlag() == other.hasFlag());
      if (hasFlag()) {
        result = result && (getFlag()
            == other.getFlag());
      }
      result = result && (hasSrc() == other.hasSrc());
      if (hasSrc()) {
        result = result && getSrc()
            .equals(other.getSrc());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFlag()) {
        hash = (37 * hash) + FLAG_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getFlag());
      }
      if (hasSrc()) {
        hash = (37 * hash) + SRC_FIELD_NUMBER;
        hash = (53 * hash) + getSrc().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.RenameStateProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.giraffa.GiraffaProtos.RenameStateProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.giraffa.GiraffaProtos.RenameStateProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_RenameStateProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_RenameStateProto_fieldAccessorTable;
      }
      
      // Construct using org.apache.giraffa.GiraffaProtos.RenameStateProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        flag_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        src_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.giraffa.GiraffaProtos.RenameStateProto.getDescriptor();
      }
      
      public org.apache.giraffa.GiraffaProtos.RenameStateProto getDefaultInstanceForType() {
        return org.apache.giraffa.GiraffaProtos.RenameStateProto.getDefaultInstance();
      }
      
      public org.apache.giraffa.GiraffaProtos.RenameStateProto build() {
        org.apache.giraffa.GiraffaProtos.RenameStateProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.giraffa.GiraffaProtos.RenameStateProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.giraffa.GiraffaProtos.RenameStateProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.giraffa.GiraffaProtos.RenameStateProto buildPartial() {
        org.apache.giraffa.GiraffaProtos.RenameStateProto result = new org.apache.giraffa.GiraffaProtos.RenameStateProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.src_ = src_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.giraffa.GiraffaProtos.RenameStateProto) {
          return mergeFrom((org.apache.giraffa.GiraffaProtos.RenameStateProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.giraffa.GiraffaProtos.RenameStateProto other) {
        if (other == org.apache.giraffa.GiraffaProtos.RenameStateProto.getDefaultInstance()) return this;
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasSrc()) {
          setSrc(other.getSrc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFlag()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              flag_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              src_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool flag = 1;
      private boolean flag_ ;
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getFlag() {
        return flag_;
      }
      public Builder setFlag(boolean value) {
        bitField0_ |= 0x00000001;
        flag_ = value;
        onChanged();
        return this;
      }
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = false;
        onChanged();
        return this;
      }
      
      // optional bytes src = 2;
      private com.google.protobuf.ByteString src_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasSrc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getSrc() {
        return src_;
      }
      public Builder setSrc(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        src_ = value;
        onChanged();
        return this;
      }
      public Builder clearSrc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        src_ = getDefaultInstance().getSrc();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:giraffa.RenameStateProto)
    }
    
    static {
      defaultInstance = new RenameStateProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:giraffa.RenameStateProto)
  }
  
  public interface FileLeaseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string holder = 1;
    boolean hasHolder();
    String getHolder();
    
    // optional uint64 lastUpdate = 2;
    boolean hasLastUpdate();
    long getLastUpdate();
  }
  public static final class FileLeaseProto extends
      com.google.protobuf.GeneratedMessage
      implements FileLeaseProtoOrBuilder {
    // Use FileLeaseProto.newBuilder() to construct.
    private FileLeaseProto(Builder builder) {
      super(builder);
    }
    private FileLeaseProto(boolean noInit) {}
    
    private static final FileLeaseProto defaultInstance;
    public static FileLeaseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public FileLeaseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_FileLeaseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_FileLeaseProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string holder = 1;
    public static final int HOLDER_FIELD_NUMBER = 1;
    private java.lang.Object holder_;
    public boolean hasHolder() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getHolder() {
      java.lang.Object ref = holder_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          holder_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHolderBytes() {
      java.lang.Object ref = holder_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        holder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint64 lastUpdate = 2;
    public static final int LASTUPDATE_FIELD_NUMBER = 2;
    private long lastUpdate_;
    public boolean hasLastUpdate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getLastUpdate() {
      return lastUpdate_;
    }
    
    private void initFields() {
      holder_ = "";
      lastUpdate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHolder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHolderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, lastUpdate_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHolderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, lastUpdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.giraffa.GiraffaProtos.FileLeaseProto)) {
        return super.equals(obj);
      }
      org.apache.giraffa.GiraffaProtos.FileLeaseProto other = (org.apache.giraffa.GiraffaProtos.FileLeaseProto) obj;
      
      boolean result = true;
      result = result && (hasHolder() == other.hasHolder());
      if (hasHolder()) {
        result = result && getHolder()
            .equals(other.getHolder());
      }
      result = result && (hasLastUpdate() == other.hasLastUpdate());
      if (hasLastUpdate()) {
        result = result && (getLastUpdate()
            == other.getLastUpdate());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasHolder()) {
        hash = (37 * hash) + HOLDER_FIELD_NUMBER;
        hash = (53 * hash) + getHolder().hashCode();
      }
      if (hasLastUpdate()) {
        hash = (37 * hash) + LASTUPDATE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getLastUpdate());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.giraffa.GiraffaProtos.FileLeaseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.giraffa.GiraffaProtos.FileLeaseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.giraffa.GiraffaProtos.FileLeaseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_FileLeaseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.giraffa.GiraffaProtos.internal_static_giraffa_FileLeaseProto_fieldAccessorTable;
      }
      
      // Construct using org.apache.giraffa.GiraffaProtos.FileLeaseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        holder_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.giraffa.GiraffaProtos.FileLeaseProto.getDescriptor();
      }
      
      public org.apache.giraffa.GiraffaProtos.FileLeaseProto getDefaultInstanceForType() {
        return org.apache.giraffa.GiraffaProtos.FileLeaseProto.getDefaultInstance();
      }
      
      public org.apache.giraffa.GiraffaProtos.FileLeaseProto build() {
        org.apache.giraffa.GiraffaProtos.FileLeaseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.giraffa.GiraffaProtos.FileLeaseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.giraffa.GiraffaProtos.FileLeaseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.giraffa.GiraffaProtos.FileLeaseProto buildPartial() {
        org.apache.giraffa.GiraffaProtos.FileLeaseProto result = new org.apache.giraffa.GiraffaProtos.FileLeaseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.holder_ = holder_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastUpdate_ = lastUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.giraffa.GiraffaProtos.FileLeaseProto) {
          return mergeFrom((org.apache.giraffa.GiraffaProtos.FileLeaseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.giraffa.GiraffaProtos.FileLeaseProto other) {
        if (other == org.apache.giraffa.GiraffaProtos.FileLeaseProto.getDefaultInstance()) return this;
        if (other.hasHolder()) {
          setHolder(other.getHolder());
        }
        if (other.hasLastUpdate()) {
          setLastUpdate(other.getLastUpdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHolder()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              holder_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lastUpdate_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string holder = 1;
      private java.lang.Object holder_ = "";
      public boolean hasHolder() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getHolder() {
        java.lang.Object ref = holder_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          holder_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHolder(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        holder_ = value;
        onChanged();
        return this;
      }
      public Builder clearHolder() {
        bitField0_ = (bitField0_ & ~0x00000001);
        holder_ = getDefaultInstance().getHolder();
        onChanged();
        return this;
      }
      void setHolder(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        holder_ = value;
        onChanged();
      }
      
      // optional uint64 lastUpdate = 2;
      private long lastUpdate_ ;
      public boolean hasLastUpdate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getLastUpdate() {
        return lastUpdate_;
      }
      public Builder setLastUpdate(long value) {
        bitField0_ |= 0x00000002;
        lastUpdate_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastUpdate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastUpdate_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:giraffa.FileLeaseProto)
    }
    
    static {
      defaultInstance = new FileLeaseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:giraffa.FileLeaseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_giraffa_UnlocatedBlockProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_giraffa_UnlocatedBlockProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_giraffa_RenameStateProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_giraffa_RenameStateProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_giraffa_FileLeaseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_giraffa_FileLeaseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrfa.proto\022\007giraffa\032\nhdfs.proto\032\016Secur" +
      "ity.proto\"\221\001\n\023UnlocatedBlockProto\022*\n\001b\030\001" +
      " \002(\0132\037.hadoop.hdfs.ExtendedBlockProto\022\016\n" +
      "\006offset\030\002 \002(\004\022\017\n\007corrupt\030\003 \002(\010\022-\n\nblockT" +
      "oken\030\004 \002(\0132\031.hadoop.common.TokenProto\"-\n" +
      "\020RenameStateProto\022\014\n\004flag\030\001 \002(\010\022\013\n\003src\030\002" +
      " \001(\014\"4\n\016FileLeaseProto\022\016\n\006holder\030\001 \002(\t\022\022" +
      "\n\nlastUpdate\030\002 \001(\004B&\n\022org.apache.giraffa" +
      "B\rGiraffaProtos\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_giraffa_UnlocatedBlockProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_giraffa_UnlocatedBlockProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_giraffa_UnlocatedBlockProto_descriptor,
              new java.lang.String[] { "B", "Offset", "Corrupt", "BlockToken", },
              org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto.class,
              org.apache.giraffa.GiraffaProtos.UnlocatedBlockProto.Builder.class);
          internal_static_giraffa_RenameStateProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_giraffa_RenameStateProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_giraffa_RenameStateProto_descriptor,
              new java.lang.String[] { "Flag", "Src", },
              org.apache.giraffa.GiraffaProtos.RenameStateProto.class,
              org.apache.giraffa.GiraffaProtos.RenameStateProto.Builder.class);
          internal_static_giraffa_FileLeaseProto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_giraffa_FileLeaseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_giraffa_FileLeaseProto_descriptor,
              new java.lang.String[] { "Holder", "LastUpdate", },
              org.apache.giraffa.GiraffaProtos.FileLeaseProto.class,
              org.apache.giraffa.GiraffaProtos.FileLeaseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.apache.hadoop.hdfs.protocol.proto.HdfsProtos.getDescriptor(),
          org.apache.hadoop.security.proto.SecurityProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
